/*
 * services/resumeBuilderService.js — builds a resume draft entirely
 * from the student's REAL portal data (never invents skills, projects,
 * certifications, marks, or experience). Mirrors the design already
 * used by services/assistantService.js:
 *
 *  - Every factual section (skills, certifications, projects,
 *    assessment) is read straight from the database for the
 *    authenticated student — never trusted from the request body, so
 *    a tampered client can't inject a fake certification into its own
 *    resume.
 *  - "Profile" fields (name/target role/degree/bio/etc.) come from the
 *    student's own profile — this project keeps most of that in the
 *    frontend's localStorage-backed profile (see js/app-student.js
 *    renderProfileTab), not a backend table, so those specific fields
 *    are accepted from the request and merged over the backend
 *    student_profiles row where that row has a value.
 *  - Experience/achievements have no dedicated tracker anywhere in
 *    this project, so they are the student's own free-text lines
 *    (typed into the resume builder) — still real, student-provided
 *    information, never fabricated by this service.
 *  - An external LLM (services/llmProvider.js) is optional and, when
 *    configured, is used ONLY to write/rewrite the professional
 *    summary from the exact facts assembled below — it is explicitly
 *    told never to add a skill, project, certification, employer, or
 *    number that isn't in the facts it's given. Every other section
 *    (skills, certifications, projects, experience, achievements) is
 *    formatted deterministically by this file, not generated by the
 *    LLM, so there is nothing there for it to invent.
 */

const skillsDb = require("../db/skills");
const certificationsDb = require("../db/certifications");
const projectsDb = require("../db/projects");
const assessmentsDb = require("../db/assessments");
const profilesDb = require("../db/profiles");
const llmProvider = require("./llmProvider");

const MAX_LINES = 20;
const MAX_LINE_LENGTH = 300;

function clamp(value, max) {
  return typeof value === "string" ? value.trim().slice(0, max) : "";
}

// Splits a textarea's raw text into clean, non-empty lines (used for
// the student-typed experience/achievements input) — trims each line,
// drops blanks, and caps how many/how long so a pasted essay can't
// blow up the resume or the LLM prompt.
function linesFromText(raw) {
  if (typeof raw !== "string") return [];
  return raw.split("\n").map((l) => clamp(l, MAX_LINE_LENGTH)).filter(Boolean).slice(0, MAX_LINES);
}

// Capitalizes the first letter and ensures the line ends with
// punctuation — the only "formatting improvement" applied without an
// LLM, so bullets look tidy even when no AI provider is configured.
function tidyLine(line) {
  const trimmed = line.trim();
  if (!trimmed) return trimmed;
  const capitalized = trimmed[0].toUpperCase() + trimmed.slice(1);
  return /[.!?]$/.test(capitalized) ? capitalized : `${capitalized}.`;
}

// ---- Gather real, authoritative facts for one student -------------------

function gatherFacts(userId, profileOverrides = {}) {
  const backendProfile = profilesDb.findByUserId(userId);
  const skillRows = skillsDb.listByUserId(userId);
  const certRows = certificationsDb.listByUserId(userId);
  const projectRows = projectsDb.listByUserId(userId);
  const assessmentRows = assessmentsDb.listByStudentUserId(userId);

  const technicalSkills = skillRows.filter((r) => r.category !== "soft").map((r) => ({ name: r.skill_name, proficiency: r.proficiency || null }));
  const softSkills = skillRows.filter((r) => r.category === "soft").map((r) => ({ name: r.skill_name, proficiency: r.proficiency || null }));

  const certifications = certRows.map((c) => ({
    name: c.name,
    organization: c.organization || null,
    issueDate: c.issue_date || null,
    skills: certificationsDb.listSkillNames(c.id),
  }));

  const projects = projectRows.map((p) => ({
    title: p.title,
    description: p.description || null,
    technologies: p.technologies || null,
    projectUrl: p.project_url || null,
  }));

  const latestAssessment = assessmentRows[0]
    ? { overallScore: assessmentRows[0].score, skillScores: Object.fromEntries(assessmentsDb.getSkillResults(assessmentRows[0].id).map((r) => [r.skill_name, r.score])) }
    : null;

  return {
    name: clamp(profileOverrides.name, 120),
    email: clamp(profileOverrides.email, 150),
    targetRole: clamp(profileOverrides.targetRole, 100),
    degree: clamp(profileOverrides.degree, 150),
    careerInterests: clamp(profileOverrides.careerInterests, 200),
    college: clamp(backendProfile?.college || profileOverrides.college, 150),
    department: clamp(backendProfile?.department || profileOverrides.department, 100),
    year: clamp(backendProfile?.year || profileOverrides.year, 40),
    bio: clamp(backendProfile?.bio || profileOverrides.bio, 800),
    phone: clamp(backendProfile?.phone || profileOverrides.phone, 40),
    location: clamp(backendProfile?.location || profileOverrides.location, 120),
    technicalSkills,
    softSkills,
    certifications,
    projects,
    assessment: latestAssessment,
    experience: linesFromText(profileOverrides.experienceText),
    achievements: linesFromText(profileOverrides.achievementsText),
  };
}

// ---- Deterministic (no-AI) formatting -----------------------------------

function buildDeterministicSummary(facts) {
  const roleLabel = facts.targetRole || facts.careerInterests || facts.department || "student";
  const topSkills = facts.technicalSkills.slice(0, 5).map((s) => s.name);
  const parts = [];
  parts.push(`${facts.name || "A motivated student"}${facts.degree ? `, pursuing ${facts.degree}` : ""}${facts.college ? ` at ${facts.college}` : ""}, aspiring to build a career as a ${roleLabel}.`);
  if (topSkills.length) parts.push(`Skilled in ${topSkills.join(", ")}.`);
  if (facts.certifications.length) parts.push(`Certified in ${facts.certifications.slice(0, 3).map((c) => c.name).join(", ")}.`);
  if (facts.projects.length) parts.push(`Hands-on experience from ${facts.projects.length} academic/personal project${facts.projects.length === 1 ? "" : "s"}.`);
  return parts.join(" ");
}

function buildDeterministicBullets(facts) {
  return {
    projectBullets: facts.projects.map((p) => tidyLine(
      p.description ? p.description : `Built ${p.title}${p.technologies ? ` using ${p.technologies}` : ""}`
    )),
    experienceBullets: facts.experience.map(tidyLine),
    achievementBullets: facts.achievements.map(tidyLine),
  };
}

// ---- Optional AI pass (summary only — see file header) -------------------

async function generateAiSummary(facts) {
  if (!llmProvider.isConfigured()) return null;

  const system = [
    "You write professional resume summaries for students on the Academia-Industry Collaboration Portal (Skillhouse).",
    "You will be given a JSON object of a student's REAL, verified facts (education, skills, certifications, projects, experience, achievements).",
    "Write ONE professional summary paragraph (3-4 sentences, no bullet points, no markdown) for this student's resume, written for the target role given.",
    "Rules you must never break:",
    "- Use ONLY the facts given below. Never invent a skill, project, certification, employer, grade, score, or number that is not present in the facts.",
    "- Never exaggerate seniority (e.g. do not call a student a 'senior' or claim years of experience they do not have).",
    "- Prioritize and phrase the given skills/projects/certifications in a way that is most relevant to the target role, but do not add anything.",
    "- Output ONLY the summary paragraph text, with no preamble, no quotes, and no labels.",
    `Facts: ${JSON.stringify(facts)}`,
  ].join("\n");

  try {
    const text = await llmProvider.complete(system, [{ role: "user", content: `Write the professional summary for target role: ${facts.targetRole || "a role matching this student's skills"}.` }]);
    return clamp(text, 900) || null;
  } catch {
    return null; // graceful fallback to the deterministic summary — never surface the LLM error
  }
}

// ---- Main entry point ----------------------------------------------------

// Returns { facts, summary, aiGenerated, ...bullets } — a draft only;
// nothing is persisted here (backend/routes/resume.js's PUT does that
// once the student has reviewed/edited it).
async function buildDraft(userId, profileOverrides) {
  const facts = gatherFacts(userId, profileOverrides);
  const bullets = buildDeterministicBullets(facts);
  const aiSummary = await generateAiSummary(facts);
  const summary = aiSummary || buildDeterministicSummary(facts);
  return { facts, summary, aiGenerated: !!aiSummary, ...bullets };
}

module.exports = { gatherFacts, buildDeterministicSummary, buildDeterministicBullets, generateAiSummary, buildDraft };
